name: Deploy Backend to ECR

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "pom.xml"
      - "Dockerfile"
      - ".github/workflows/backend-deploy.yml"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build Spring Boot application
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin \
          410126553447.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        working-directory: backend
        run: |
          docker build -t backend .

      - name: Tag Docker image
        run: |
          docker tag backend:latest \
          410126553447.dkr.ecr.ap-south-1.amazonaws.com/backend:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
          410126553447.dkr.ecr.ap-south-1.amazonaws.com/backend:latest